"""Component ids. Kept in one place so callbacks and layouts cannot drift apart."""

# shell
URL = "url"
PERSONA = "persona-store"
PERSONA_SELECT = "persona-select"
NAV_VERSION = "nav-version"
NAV_SEARCH = "nav-search"
NAVBAR = "navbar-content"
PAGE = "page-content"
NOTIFY = "notifications"
DOWNLOAD = "download"

# form page
FORM_KEY = "form-key"
DRAFT = "draft-store"
GRID_VERSION = "grid-version"
GRID = "grid"
GRID_SEARCH = "grid-search"
GRID_AUDIT = "grid-audit"
GRID_REFRESH = "grid-refresh"
GRID_ADD = "grid-add"
GRID_DELETE = "grid-delete"
GRID_SAVE = "grid-save"
GRID_DISCARD = "grid-discard"
GRID_CSV = "grid-export-csv"
GRID_XLSX = "grid-export-xlsx"
GRID_CAPTION = "grid-caption"
PENDING = "pending-bar"
SAVE_RESULT = "save-result"
FORM_TABS = "form-tabs"
HISTORY_PANEL = "history-panel"
SCHEMA_PANEL = "schema-panel"
SCHEMA_GRID = "schema-grid"
SCHEMA_SAVE = "schema-save"
SCHEMA_RESULT = "schema-result"
ADD_COL_OPEN = "add-col-open"
ADD_COL_MODAL = "add-col-modal"
ADD_COL_NAME = "add-col-name"
ADD_COL_TYPE = "add-col-type"
ADD_COL_DESC = "add-col-desc"
ADD_COL_PRECISION = "add-col-precision"
ADD_COL_SCALE = "add-col-scale"
ADD_COL_SUBMIT = "add-col-submit"
DROP_COL_OPEN = "drop-col-open"
DROP_COL_MODAL = "drop-col-modal"
DROP_COL_SELECT = "drop-col-select"
DROP_COL_CONFIRM = "drop-col-confirm"
DROP_COL_SUBMIT = "drop-col-submit"
SETTINGS_DISPLAY = "settings-display-name"
SETTINGS_DESC = "settings-description"
SETTINGS_OWNER = "settings-owner"
SETTINGS_SAVE = "settings-save"
SETTINGS_RESULT = "settings-result"
DROP_FORM_CONFIRM = "drop-form-confirm"
DROP_FORM_SUBMIT = "drop-form-submit"
IMPORT_OPEN = "import-open"
IMPORT_MODAL = "import-modal"
IMPORT_UPLOAD = "import-upload"
IMPORT_SHEET = "import-sheet"
IMPORT_PREVIEW = "import-preview"
IMPORT_SUBMIT = "import-submit"
IMPORT_TOKEN = "import-token"

# form creator
WIZ_STORE = "wizard-store"
WIZ_STEPPER = "wizard-stepper"
WIZ_BODY = "wizard-body"
WIZ_MODE = "wiz-mode"
WIZ_UPLOAD = "wiz-upload"
WIZ_SHEET = "wiz-sheet"
WIZ_HEADER_ROW = "wiz-header-row"
WIZ_PREVIEW = "wiz-preview"
WIZ_NEXT = "wiz-next"
WIZ_BACK = "wiz-back"
WIZ_CANCEL = "wiz-cancel"
WIZ_COLUMNS_GRID = "wiz-columns-grid"
WIZ_ADD_COLUMN = "wiz-add-column"
WIZ_DOMAIN = "wiz-domain"
WIZ_NAME = "wiz-name"
WIZ_DISPLAY = "wiz-display"
WIZ_DESC = "wiz-desc"
WIZ_OWNER = "wiz-owner"
WIZ_LOAD_ROWS = "wiz-load-rows"
WIZ_EFFECTIVE = "wiz-effective"
WIZ_CREATE = "wiz-create"
WIZ_ERRORS = "wiz-errors"

# home / help
HOME_FILTER = "home-filter"
HOME_CARDS = "home-cards"
HELP_TABS = "help-tabs"
HISTORY_FILTER = "history-filter"
HISTORY_GRID = "history-grid"

# domain pages
DOMAIN_KEY = "domain-key"
DOMAIN_DOC_LINK = "domain-doc-link"
DOMAIN_FORMS_FILTER = "domain-forms-filter"
DOMAIN_FORMS = "domain-forms"
GRANTS_FILTER = "grants-filter"
NEW_DOMAIN_DOC_LINK = "new-domain-doc-link"
DOMAIN_DISPLAY = "domain-display-name"
DOMAIN_DESC = "domain-description"
DOMAIN_OWNER = "domain-owner"
DOMAIN_SAVE = "domain-save"
DOMAIN_RESULT = "domain-result"
GRANT_PRINCIPAL = "grant-principal"
GRANT_ROLE = "grant-role"
GRANT_SUBMIT = "grant-submit"
GRANTS_TABLE = "grants-table"
NEW_DOMAIN_NAME = "new-domain-name"
NEW_DOMAIN_DISPLAY = "new-domain-display"
NEW_DOMAIN_DESC = "new-domain-desc"
NEW_DOMAIN_OWNER = "new-domain-owner"
NEW_DOMAIN_SUBMIT = "new-domain-submit"
NEW_DOMAIN_RESULT = "new-domain-result"


def revoke_id(principal: str) -> dict:
    return {"type": "revoke", "principal": principal}
