#!/usr/bin/env python
"""Vendor the Tabler icons the UI uses into ``assets/icons/`` and generate ``assets/icons.css``.

The app renders icons from local SVG files (``rdm.ui.components.icon``), so nothing is fetched
from a CDN at runtime - Databricks Apps deployments in locked-down networks show every icon.
Run this after adding an icon name (``tabler:<name>``) to the Python sources:

    python scripts/vendor_icons.py            # download missing icons, rewrite icons.css
    python scripts/vendor_icons.py --prune    # also delete SVGs no longer referenced

Icons come from https://github.com/tabler/tabler-icons (MIT, see assets/icons/tabler/LICENSE).
"""

from __future__ import annotations

import argparse
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
ICON_DIR = ROOT / "assets" / "icons" / "tabler"
CSS = ROOT / "assets" / "icons.css"
TABLER_VERSION = "3.46.0"
RAW_URL = "https://raw.githubusercontent.com/tabler/tabler-icons/v{version}/icons/outline/{name}.svg"
NAME_RE = re.compile(r"tabler:([a-z0-9-]+)")


def used_icons() -> set[str]:
    """Every ``tabler:<name>`` mentioned in the Python sources."""
    return {m for path in SRC.rglob("*.py") for m in NAME_RE.findall(path.read_text(encoding="utf-8"))}


def compact(svg: str) -> str:
    """One-line SVG without the Tabler class attribute (the app styles icons itself)."""
    svg = re.sub(r'\s+class="[^"]*"', "", svg)
    return re.sub(r"\s+", " ", svg).replace("> <", "><").strip()


def fetch(name: str) -> str:
    with urllib.request.urlopen(RAW_URL.format(version=TABLER_VERSION, name=name), timeout=30) as resp:  # noqa: S310
        return resp.read().decode("utf-8")


def write_css(names: set[str]) -> None:
    lines = [
        "/* Generated by scripts/vendor_icons.py - do not edit. One class per icon used in src/rdm;",
        "   the URL is relative to this file so it resolves under any application path prefix. */",
    ]
    lines += [f'.rdm-icon-{n} {{ --rdm-icon: url("icons/tabler/{n}.svg"); }}' for n in sorted(names)]
    CSS.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--prune", action="store_true", help="delete SVG files no longer referenced")
    args = parser.parse_args()
    ICON_DIR.mkdir(parents=True, exist_ok=True)
    names = used_icons()
    added = 0
    for name in sorted(names):
        target = ICON_DIR / f"{name}.svg"
        if target.exists():
            continue
        try:
            target.write_text(compact(fetch(name)), encoding="utf-8")
        except Exception as exc:  # noqa: BLE001
            print(f"error: could not fetch icon '{name}': {exc}", file=sys.stderr)
            return 1
        added += 1
    pruned = 0
    if args.prune:
        for path in ICON_DIR.glob("*.svg"):
            if path.stem not in names:
                path.unlink()
                pruned += 1
    write_css(names)
    print(
        f"{len(names)} icons referenced, {added} downloaded, {pruned} pruned; wrote {CSS.relative_to(ROOT)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
